### PR TITLE
Fixes to the Web Bluetooth examples' service worker

### LINKED ISSUE #447: Web Bluetooth Service workers console errors
```
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
(unknown) 'webkitIDBTransaction' is deprecated. Please use 'IDBTransaction' instead.
(unknown) 'webkitIDBRequest' is deprecated. Please use 'IDBRequest' instead.
(unknown) 'webkitIDBObjectStore' is deprecated. Please use 'IDBObjectStore' instead.
(unknown) 'webkitIDBKeyRange' is deprecated. Please use 'IDBKeyRange' instead.
(unknown) 'webkitIDBIndex' is deprecated. Please use 'IDBIndex' instead.
(unknown) 'webkitIDBFactory' is deprecated. Please use 'IDBFactory' instead.
(unknown) 'webkitIDBDatabase' is deprecated. Please use 'IDBDatabase' instead.
(unknown) 'webkitIDBCursor' is deprecated. Please use 'IDBCursor' instead.
service-worker.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
service-worker.js:3 Uncaught (in promise) TypeError: Failed to execute 'clone' on 'Response': Response body is already used
    at caches.open.then.cache (service-worker.js:3)
```

@jeffposnick Any idea what is happening at https://googlechrome.github.io/samples/web-bluetooth/device-info.html in Chrome	56.0.2920.0 (Official Build) dev (64-bit)?

### PR DESCRIPTION
**Pull request by jeffposnick**
R @beaufortfrancois 

This fixes #447.

I don't think there's any reason to perform runtime caching of cross-origin requests in any of the Bluetooth samples, so it seemed like a good idea to add in the same-origin check inside the `fetch` handler. If you know of a reason to do cache them, we can remove that check.

### CODE REVIEW

File: web-bluetooth/service-worker.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 function addToCache(request, networkResponse) {
   return caches.open('web-bluetooth')
-    .then(cache => cache.put(request, networkResponse.clone()));
+    .then(cache => cache.put(request, networkResponse));
```
Comment (beaufortfrancois) [inline web-bluetooth/service-worker.js:3]: If we do `clone()` there, we don't need it when calling `addToCache` right?

Comment (jeffposnick) [reply web-bluetooth/service-worker.js:3]: This PR moved the `clone()` out of `addToCache()`, yes. So I think it's already doing what you're suggesting.

You might be confused based on the partial diffs?

Comment (beaufortfrancois) [reply web-bluetooth/service-worker.js:3]: I was. Sorry for that and thanks for the PR ;)

**Review by beaufortfrancois — APPROVED** [review]
